approve 화면 개선
elysia-dev/hazelnut pull request #10
Opened 2021-09-10 04:16 UTC by JUNG-gyucheol

- 스테이킹과 상품구매 할 때 approve 화면을 개선

2021-09-13 07:07 UTC, leegakyeong requested changes
코드 확인했습니다! 생각해 보니까 저는 헤이즐넛에서 린팅을 꺼 놓은 것 같은데 도로 켜놔야겠네요...ㅎㅎ
이번 풀리퀘스트는 거의 UI 관련된 부분이었던 것 같아서 제 생각에는 별로 고쳐야 할 부분은 없어보입니다! 

그런데 너무 늦게 생각난 것 같긴 한데... 스테이킹을 할 때는 `ConfirmModal`과 `ApproveStep`에서 보여주는 내용이 거의 똑같지 않나요..?? 심각한 문제는 아니지만 약간 불필요하게 반복되는 부분인 것 같습니다! 시간이 있다면 개선 방안을 다시 찾아봐도 좋을 것 같네용. 지금 모달로 보여주는 것들을 그냥 바로 스크린에 보여 줘도 좋을 것 같습니다! 이건 동욱님 의견도 들어봐야겠네요!

2021-09-13 07:07 UTC, leegakyeong commented on src/core/langs/ko.json
> +      "approve_guide_second": "최초 구매 시에만 승인이 필요하며, 승인이 성공적으로\n완료될 경우, 이후의 거래에는 권한 승인이 없이 부동산\n토큰을 구매하실 수 있습니다."
아직 영어랑 중국어는 번역이 안 된 거 맞나요?!

2021-09-13 07:07 UTC, leegakyeong commented on src/components/ConfirmModal.tsx
> +      {' '}
이거 지워주세요~!

2021-09-13 07:07 UTC, leegakyeong commented on src/containers/Stake.tsx
> +            Number(utils.formatEther(res)) > Number(transactionRequest.value)
이 부분 `gte()` 대신 `>`로 바꾸신 이유가 있을까요? 뭔가 overflow 문제가 생길 수도 있을 것 같아 여쭤봅니다!

2021-09-14 01:37 UTC, JUNG-gyucheol commented on src/core/langs/ko.json
> +      "approve_guide_second": "최초 구매 시에만 승인이 필요하며, 승인이 성공적으로\n완료될 경우, 이후의 거래에는 권한 승인이 없이 부동산\n토큰을 구매하실 수 있습니다."
네 아직 안됐습니다.

2021-09-14 01:38 UTC, JUNG-gyucheol commented on src/containers/Stake.tsx
> +            Number(utils.formatEther(res)) > Number(transactionRequest.value)
비교를 못해서 변경했습니다. 다시 확인해보겠습니다.

2021-09-14 04:39 UTC, donguks approved these changes
잘확인했습니다!

사소한것들만 고치면 머지해도됩니다!

2021-09-14 04:39 UTC, donguks commented on src/components/ConfirmModal.tsx
> +                  fontFamily: 'Spoqa Han Sans',
font는 enum으로 해두면 더 좋을것 같긴합니다. 이렇게 string으로 계속 사용하는데는 불편함이 있을 것 같아요!

2021-09-14 04:39 UTC, donguks commented on src/containers/Stake.tsx
> +            Number(utils.formatEther(res)) > Number(transactionRequest.value)
Number로 사용할경우 BigNumber라 overflow되기 쉽습니다!

2021-09-16 05:53 UTC, leegakyeong approved these changes
확인했습니다! 고생하셨습니다!!

2021-09-16 06:14 UTC, merged