네트워크가 변경 및 연동
elysia-dev/hazelnut pull request #2
Opened 2021-07-09 12:31 UTC by JUNG-gyucheol

### 네트워크 변경 및 연동
- ducth앱에서 바로 url로 데이터를 전달하면 `productId` 만  espresso로 넘겨주고 건물의 정보를  가져옴.
- 코인 시세는 `coingecko` 를 사용
- 소수점은 `ehters.js` 의 `utils.parseUnit` 을 사용하여 변환한 다음 계산하여 expectedValue 값 출력
- connect wallet 클릭 시 네트워크를 변경하는 창이 표시되도록 구현
- 설정된 네트워크가 없으면 자동으로 추가되도록 구현
- 네트워크를 변경안하고 진행시 `네트워크가 일치하지않습니다.` 라는 경고창을 표시하고 다시 네트워크를 변경할 수 있는 창 표시
- 데스크탑에서는 네트워크를 변경하고 난 뒤 첫 화면으로 바뀌지 않아 하단에 유저가 가지고 있는 코인을 `chainId` 가 변경되면 자동으로 변경되도록 구현 
### 문제점
- 데스크탑에서는 `method: 'wallet_switchEthereumChain'` 사용가능하지만 모바일에서는 에러발생
- 모바일에서는  `method: 'wallet_addEthereumChain'` 사용하여 네트워크를 추가도 해주지만 변경도 해주지만 데스크탑에서는 기본적으로 설정되어 있는 네트워크들이랑 겹치면 에러발생

2021-07-11 12:11 UTC, donguks requested changes
코드 잘 확인했습니다.
Dutch ~ Hazelnut 스위칭 사이에서 Espresso의 의존성을 제거 할 수 있어서 좋았습니다!
다만, 현재 코드는 호환성이 없어서 호환성을 보장하도록 작업을 변경해주셔야할 것 같아요.
코드가 잘 작동하려면, Dutch와 Hazelnut이 동시에 배포가 되어야만 하는 제약이 생깁니다.
따라서 이런 제약 없이, Hazelnut은 이전 버전의 Dutch의 요청을 잘 처리하기 위해 기존 Espresso에 의존하는 방식을 여전히 구현하고 있어야하며, 새로운 url방식은 아예 다른 기능으로 추가되어야만 합니다.

2021-07-11 12:11 UTC, donguks commented on src/core/utils/createNetwork.ts
> +import { BigNumber } from "ethers";
파일의 인덴트가 다른 파일과 같지 않습니다.

2021-07-11 12:11 UTC, donguks commented on src/core/utils/createNetwork.ts
> +                    rpcUrls: ["https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"],
뒤 api key는 환경변수로 변경해주세요~

2021-07-11 12:11 UTC, donguks commented on src/core/utils/createNetwork.ts
> +export async function createKovan (library: any) {
NODE_ENV를 이용하지 않고 환경변수를 이용하는게 더 편할 것 같습니다. 그러면, 중복을 줄이고 if문을 없앨 수 있을 것 같아요!

2021-07-11 12:11 UTC, donguks commented on src/core/utils/createNetwork.ts
> +export  function isCheckChainId (productPayment: string, chainId: string): boolean {
함수의 이름이 명확하지 않습니다.
역할은 isValidChainId 와 같은 느낌이네요!

2021-07-11 12:11 UTC, donguks commented on src/core/utils/createNetwork.ts
> +    if(productPayment === PaymentMethod.BNB){
환경변수를 잘 정의 하면 이렇게 조건문이 많지 않아도 되고, "alert"의 반복도 있지 않을 것 같아요!

2021-07-11 12:11 UTC, donguks commented on src/hooks/useExpectedValue.ts
> +        value: BigNumber.from(utils.parseUnits(amount,decimalCount).toHexString() || 0)
`utils.parseUnits(amount || "0",decimalCount)` 으로 정의해도 동일한 변수입니다.

2021-07-11 12:11 UTC, donguks commented on src/hooks/useExpectedValue.ts
> +            .div(transactionRequest.product.paymentMethod === PaymentMethod.ETH ? ethPrice : transactionRequest.product.paymentMethod === PaymentMethod.BNB ? bnbPrice : elPrice)
음 삼항연산자가 더 복잡해지는 것 같네요! paymentMethod를 넘겨주면 그 에 맞는 가격을 리턴해주는 함수를 새로 만드는 편이 나을 것 같습니다.

2021-07-11 12:11 UTC, donguks commented on src/core/types/CoinPriceResponse.ts
> +
인덴트가 맞지 않습니다~

2021-07-11 12:11 UTC, donguks commented on src/core/enums/NetworkChainId.tsx
> +enum NetworkChainId {
인덴트가 맞지 않아요 ㅜㅜ

2021-07-11 12:11 UTC, donguks commented on src/containers/Buying.tsx
> +  }, [!account && !chainId]);
useEffect 의존성에는 연산자를 붙일 필요가 없습니다. `[account, chainId]`로 작성해도 됩니다!

2021-07-11 12:11 UTC, donguks commented on src/App.tsx
> +        <Route path="/requests/:productid/:valueto/:type/:contractaddress/:useraddress/:userlanguage">
dutch에서 리뷰를 했지만, "/"를 연속적으로 사용하는 것 보다는 Query String을 사용하는게 더 편합니다!

2021-07-12 08:20 UTC, JUNG-gyucheol commented on src/core/utils/createNetwork.ts
> +import { BigNumber } from "ethers";
인덴트를 맞추지 못한 부분이 많네요. 다음 스프린트 때는 조금 더 신경쓰도록 하겠습니다.

2021-07-12 08:26 UTC, JUNG-gyucheol commented on src/core/utils/createNetwork.ts
> +                    rpcUrls: ["https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"],
api key 환경변수로 설정한는 거 조금 더 신경쓰겠습니다.

2021-07-12 08:28 UTC, JUNG-gyucheol commented on src/core/utils/createNetwork.ts
> +export  function isCheckChainId (productPayment: string, chainId: string): boolean {
네이밍도 조금 더 신경써서 작성하겠습니다.

2021-07-12 09:41 UTC, JUNG-gyucheol commented on src/containers/Buying.tsx
> +  }, [!account && !chainId]);
알려주셔서 감사합니다!

2021-07-12 11:48 UTC, JUNG-gyucheol commented on src/App.tsx
> +        <Route path="/requests/:productid/:valueto/:type/:contractaddress/:useraddress/:userlanguage">
useLocation 과  query-string 을 사용하여 수정했습니다!

2021-07-12 12:00 UTC, JUNG-gyucheol commented
### 수정 사항
- 네트워크가 다르면 현재가지고 있는 코인들을 표시하지 않도록 구현했습니다.

2021-07-13 02:54 UTC, donguks requested changes

2021-07-13 02:54 UTC, donguks commented on src/components/AddressBottomTab.tsx
> +  function currentEthOrBnb (productPayment: string, chainId: string, library: any, account: string) {
인덴트가 맞지 않습니다 ㅜ

2021-07-13 02:54 UTC, donguks commented on src/components/AddressBottomTab.tsx
> +    if(productPayment === PaymentMethod.BNB){
실행하는 함수가 library.getBalance로 모두 동일해서 조건문이 필요없습니다.

2021-07-13 02:54 UTC, donguks commented on src/containers/Buying.tsx
> +  const createNetwork = async () => {
try, catch, 조건문이 잘 작동하지 않을 것 같습니다.
우선 조건문으로 크게 구분한뒤, 실제로 함수를 실행시키는 부근에만 try-catch를 붙이는게 더 좋을 것 같습니다.
지금 코드를 보고 이해한 논리는 아래와 같습니다.
```
1) BNB로 결제해야할 때 1-1) 현재 체인이 BSC가 아니면 BSC를 
2) 아니면 코반으로 네트워크 변경
1~2의 과정이 실패할 경우 
3) EL이나 ETH로 결제해야할 때 kovan을 생성
3-1)의 과정이 실패하면 console.error!
```

자바스크립트에서 함수는 1급객체이므로 변수에 할당할 수 있습니다.
따라서 Payment에 따라 네트워크를 생성하는 함수와, 네트워크로 변경하는 함수를 변수에 할당한 뒤,
그 후 변수에 할당한 함수를 실행하면서 try-catch로 진행하도록 작성하는게 더 좋을 것 같습니다.

2021-07-13 02:54 UTC, donguks commented on src/containers/Refund.tsx
> +        chainId={''}
ㅋㅋ 인덴트가..!

2021-07-13 02:54 UTC, donguks commented on src/containers/Requests.tsx
> +  const {productId, value, type, contractAddress, address, language} = queryString.parse(search);
queryString pacakge를 사용하셨군요!
요렇게 하면 변수들은 모두 어떤 type으로 정의되나요?!

2021-07-13 02:54 UTC, donguks commented on src/core/utils/createNetwork.ts
> +import { BigNumberish } from "ethers";
이 파일도 인덴트가 혼자 다르네요!

2021-07-13 04:19 UTC, JUNG-gyucheol commented on src/containers/Requests.tsx
> +  const {productId, value, type, contractAddress, address, language} = queryString.parse(search);
string , string[], null 3개의 타입으로 정의가 되더군요

2021-07-13 12:32 UTC, donguks approved these changes
사소한 것들만 해결하면, 이 풀리퀘스트는 머지해도 될 것 같습니다. 
고생하셨습니다!

2021-07-13 12:32 UTC, donguks commented on src/core/utils/createNetwork.ts
> +                    rpcUrls: [`https://kovan.infura.io/v3/${process.env.REACT_APP_KOVAN_API_KEY}`],
혹시 rpcUrls가 필요한 이유가 무엇일까요?! 없어도 되는지 혹시 확인 부탁드립니다! 
메타마스크를 통해서 이더리움과 통신할 수 있어서 따로 rpc가 필요 없을 수 있습니다.
BNB의 경우는 필요한데, kovan과 메인넷은 원래 메타마스크가 지원하는 네트워크라서 없어도 될것 같습니다.

2021-07-13 12:32 UTC, donguks commented on src/core/utils/createNetwork.ts
> +            if(chainId === process.env.REACT_APP_BNB_NETWORK){
`const requiredNetworkChainID = productPayment === PaymentMethod.BNB ? REACT_APP_BNB_NETWORK : REACT_APP_ETH_NETWORK ` 요렇게 변수로 미리 정해놓으면 코드 중복을 줄일 수 있을 것 같습니다!

2021-07-13 12:32 UTC, donguks commented on src/containers/Requests.tsx
> +                abi:JSON.stringify(product.data.paymentMethod === PaymentMethod.BNB ? ETH_abi : TokenAbi),
`paymentMethod === EL` 일때 TokenAbi이고, BNB랑 ETH는 모두 ETH_ABI를 사용해야합니다!

2021-07-13 15:13 UTC, JUNG-gyucheol commented on src/core/utils/createNetwork.ts
> +                    rpcUrls: [`https://kovan.infura.io/v3/${process.env.REACT_APP_KOVAN_API_KEY}`],
모바일에서는 따로 kovan과 mainnet을 만들어줘야해서 넣어두었습니다. 
rpcUrls를 지우고 테스트해보니까 네트워크를 변경하라는 요청이 안 뜨네요.
테스트 할 때 확인 부탁드리겠습니다.

2021-07-14 01:26 UTC, donguks commented on src/core/utils/createNetwork.ts
> +                    rpcUrls: [`https://kovan.infura.io/v3/${process.env.REACT_APP_KOVAN_API_KEY}`],
앗 그때 말씀했던 이슈가 이거였군요 하하
음 그러면 API_KEY는 공개되면 안되니, 환경변수를 gitignore에 넣어 두어야겠습니다. 우선 이건 요렇게 알겠습니다.

2021-07-14 03:29 UTC, merged