스테이킹 기능 구현
elysia-dev/hazelnut pull request #8
Opened 2021-08-20 05:46 UTC by leegakyeong

## 한 일
- 헤이즐넛에 Stake, Unstake, UnstakeAndMigrate, Reward 페이지 추가
  - 기능 구현
  - 업데이트된 디자인 시안 반영
  - 부동산 구매 관련 페이지와 구조는 거의 동일하지만 일부 코드를 간소화함
- usePrice() 함수에 ELFI, DAI 추가

## 할 일
- 문구 번역 요청
- 더치에서처럼 폰트, 색상 enum으로 빼기? (이건 나중에 헤이즐넛 전체 디자인 업데이트하면서 해도 될 듯)

2021-08-23 04:20 UTC, donguks requested changes
작업내용 잘 확인했습니다!
규철님이 구현했던것 처럼, url parameters를 이용해서 앱과 웹에서 변수들을 잘 주고 받았군요!
custom hooks를 이용해서 재활용성을 높여보고, contract-typechain을 이용해서 불필요한 코드들을 줄여보면 더 좋을것 같습니다.

2021-08-23 04:20 UTC, donguks commented on src/containers/Unstake.tsx
> +  const createTransaction = () => {
스테이킹 풀 컨트랙트와 통신하는 부분 https://github.com/elysia-dev/contract-typechain 을 이용해보는것은 어떨까요?!
populateTransaction을 하지 않아도되고, ABI 파일도 필요없으며, type casting도 하지 않아도됩니다!

2021-08-23 04:20 UTC, donguks commented on src/containers/Unstake.tsx
> +  const currentChainId = async () => {
currentChainId, networkCheck, createNetwork, checkAccount 등 반복되는 함수들이 많은데, 이번 기회에 모두 hooks로 만들고 사용해보는것은 어떨까요?!
elyfi-web에서는 기다리는 논리가 동일해서 useWating이라는 hooks를 선언하고 재활용했습니다.
hooks로 선언하면 상태값, 상태값 변경 함수, useEffect와 같은 것들을 재활용할 수 있어서 좋습니다. 또한 hooks 내부에서도 component와 마찬가지로 다른 hooks도 사용할 수 있어 매우편합니다!
https://github.com/elysia-dev/elyfi-web/blob/main/src/hooks/useWaitingTx.ts 
https://reactjs.org/docs/hooks-custom.html

2021-08-24 03:50 UTC, leegakyeong commented on src/containers/Unstake.tsx
> +  const currentChainId = async () => {
currentChainId()는 useChainId()라는 커스텀 훅으로 만들었습니다! 제대로 만든 건지는 모르겠네요,, e532134
networkCheck()와 createNetwork()는 리액트 훅을 사용하지 않는 함수고 다른 코드와 중복되는 부분이 있어서 함수 자체를 해체했습니다. 9a636c5 5a083fc
checkAccount()도 단순히 모달을 보여 주는 함수라서 이건 그대로 내버려 뒀습니다! 더 좋은 방법이 있을까요..??

2021-08-24 06:00 UTC, donguks commented on src/containers/Unstake.tsx
> +  const currentChainId = async () => {
https://github.com/elysia-dev/hazelnut/commit/e5321345a4f51b99653674928511f622033cdc8d#diff-88f8dca109ce98e29c28e5f77196505576395ae748460f48d92b8a4a24f881c0R8-R12 요렇게 구현하면, 컴포넌트가 리랜더링될때만 조건을 확인하기 때문에 의도하지 않은 결과가 나올 수 있을 것 같아요. useEffect에 의존성을 library로 설정해서 State값을 변경해주도록 구현하면 더 좋을 것 같아요! chainId를 재활용하려는 시도는 좋습니다!

2021-08-24 06:02 UTC, donguks commented on src/containers/Unstake.tsx
> +  const currentChainId = async () => {
checkAccount 정도는 요렇게 남겨두어도 괜찮을것 같긴합니다.

2021-08-24 06:15 UTC, leegakyeong commented on src/containers/Unstake.tsx
> +  const createTransaction = () => {
8378553 b0839dd d170546 0a194f6 c7c34e1

2021-08-24 07:54 UTC, leegakyeong commented on src/containers/Unstake.tsx
> +  const currentChainId = async () => {
6950604

2021-08-25 04:14 UTC, merged